# Generated by Django 4.0.5 on 2022-07-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Living Room', 'Living Room'), ('Kitchen', 'Kitchen'), ('Bathroom', 'Bathroom'), ('Bedroom', 'Bedroom'), ('Workspace', 'Workspace'), ('Accessories', 'Accessories')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('Wood', 'Wood'), ('Iron', 'Iron'), ('Ceramic', 'Ceramic'), ('Material', 'Material'), ('Glass', 'Glass')], max_length=200, null=True),
        ),
    ]
